DTO_EXTENSION = ".dto.ts"
PERSISTENCE_EXTENSION = ".persistence.ts"
ENTITY_EXTENSION = ".entity.ts"
MAPPER_EXTENSION = ".mapper.ts"
REPOSITORY_EXTENSION = ".repository.ts"
QUERY_EXTENSION = ".query.ts"
COMMAND_EXTENSION = ".command.ts"
CONTROLLER_EXTENSION = ".controller.ts"
